# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/snigdha8/jydayan2-snigdha8-saagark2-amithph2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/snigdha8/jydayan2-snigdha8-saagark2-amithph2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/snigdha8/jydayan2-snigdha8-saagark2-amithph2/CMakeFiles /home/snigdha8/jydayan2-snigdha8-saagark2-amithph2/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/snigdha8/jydayan2-snigdha8-saagark2-amithph2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test-data

# Build rule for target.
test-data: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-data
.PHONY : test-data

# fast build rule for target.
test-data/fast:
	$(MAKE) $(MAKESILENT) -f data/CMakeFiles/test-data.dir/build.make data/CMakeFiles/test-data.dir/build
.PHONY : test-data/fast

#=============================================================================
# Target rules for targets named main-data

# Build rule for target.
main-data: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-data
.PHONY : main-data

# fast build rule for target.
main-data/fast:
	$(MAKE) $(MAKESILENT) -f data/CMakeFiles/main-data.dir/build.make data/CMakeFiles/main-data.dir/build
.PHONY : main-data/fast

#=============================================================================
# Target rules for targets named DataLib

# Build rule for target.
DataLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DataLib
.PHONY : DataLib

# fast build rule for target.
DataLib/fast:
	$(MAKE) $(MAKESILENT) -f data/CMakeFiles/DataLib.dir/build.make data/CMakeFiles/DataLib.dir/build
.PHONY : DataLib/fast

#=============================================================================
# Target rules for targets named test-node

# Build rule for target.
test-node: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-node
.PHONY : test-node

# fast build rule for target.
test-node/fast:
	$(MAKE) $(MAKESILENT) -f node/CMakeFiles/test-node.dir/build.make node/CMakeFiles/test-node.dir/build
.PHONY : test-node/fast

#=============================================================================
# Target rules for targets named main-node

# Build rule for target.
main-node: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-node
.PHONY : main-node

# fast build rule for target.
main-node/fast:
	$(MAKE) $(MAKESILENT) -f node/CMakeFiles/main-node.dir/build.make node/CMakeFiles/main-node.dir/build
.PHONY : main-node/fast

#=============================================================================
# Target rules for targets named NodeLib

# Build rule for target.
NodeLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NodeLib
.PHONY : NodeLib

# fast build rule for target.
NodeLib/fast:
	$(MAKE) $(MAKESILENT) -f node/CMakeFiles/NodeLib.dir/build.make node/CMakeFiles/NodeLib.dir/build
.PHONY : NodeLib/fast

#=============================================================================
# Target rules for targets named test-graph

# Build rule for target.
test-graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-graph
.PHONY : test-graph

# fast build rule for target.
test-graph/fast:
	$(MAKE) $(MAKESILENT) -f graph/CMakeFiles/test-graph.dir/build.make graph/CMakeFiles/test-graph.dir/build
.PHONY : test-graph/fast

#=============================================================================
# Target rules for targets named main-graph

# Build rule for target.
main-graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-graph
.PHONY : main-graph

# fast build rule for target.
main-graph/fast:
	$(MAKE) $(MAKESILENT) -f graph/CMakeFiles/main-graph.dir/build.make graph/CMakeFiles/main-graph.dir/build
.PHONY : main-graph/fast

#=============================================================================
# Target rules for targets named GraphLib

# Build rule for target.
GraphLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GraphLib
.PHONY : GraphLib

# fast build rule for target.
GraphLib/fast:
	$(MAKE) $(MAKESILENT) -f graph/CMakeFiles/GraphLib.dir/build.make graph/CMakeFiles/GraphLib.dir/build
.PHONY : GraphLib/fast

#=============================================================================
# Target rules for targets named test-bfs

# Build rule for target.
test-bfs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-bfs
.PHONY : test-bfs

# fast build rule for target.
test-bfs/fast:
	$(MAKE) $(MAKESILENT) -f bfs/CMakeFiles/test-bfs.dir/build.make bfs/CMakeFiles/test-bfs.dir/build
.PHONY : test-bfs/fast

#=============================================================================
# Target rules for targets named main-bfs

# Build rule for target.
main-bfs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-bfs
.PHONY : main-bfs

# fast build rule for target.
main-bfs/fast:
	$(MAKE) $(MAKESILENT) -f bfs/CMakeFiles/main-bfs.dir/build.make bfs/CMakeFiles/main-bfs.dir/build
.PHONY : main-bfs/fast

#=============================================================================
# Target rules for targets named BFSLib

# Build rule for target.
BFSLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BFSLib
.PHONY : BFSLib

# fast build rule for target.
BFSLib/fast:
	$(MAKE) $(MAKESILENT) -f bfs/CMakeFiles/BFSLib.dir/build.make bfs/CMakeFiles/BFSLib.dir/build
.PHONY : BFSLib/fast

#=============================================================================
# Target rules for targets named test-dijkstra

# Build rule for target.
test-dijkstra: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-dijkstra
.PHONY : test-dijkstra

# fast build rule for target.
test-dijkstra/fast:
	$(MAKE) $(MAKESILENT) -f dijkstra/CMakeFiles/test-dijkstra.dir/build.make dijkstra/CMakeFiles/test-dijkstra.dir/build
.PHONY : test-dijkstra/fast

#=============================================================================
# Target rules for targets named main-dijkstra

# Build rule for target.
main-dijkstra: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-dijkstra
.PHONY : main-dijkstra

# fast build rule for target.
main-dijkstra/fast:
	$(MAKE) $(MAKESILENT) -f dijkstra/CMakeFiles/main-dijkstra.dir/build.make dijkstra/CMakeFiles/main-dijkstra.dir/build
.PHONY : main-dijkstra/fast

#=============================================================================
# Target rules for targets named DijkstraLib

# Build rule for target.
DijkstraLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DijkstraLib
.PHONY : DijkstraLib

# fast build rule for target.
DijkstraLib/fast:
	$(MAKE) $(MAKESILENT) -f dijkstra/CMakeFiles/DijkstraLib.dir/build.make dijkstra/CMakeFiles/DijkstraLib.dir/build
.PHONY : DijkstraLib/fast

#=============================================================================
# Target rules for targets named test-pagerank

# Build rule for target.
test-pagerank: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-pagerank
.PHONY : test-pagerank

# fast build rule for target.
test-pagerank/fast:
	$(MAKE) $(MAKESILENT) -f pagerank/CMakeFiles/test-pagerank.dir/build.make pagerank/CMakeFiles/test-pagerank.dir/build
.PHONY : test-pagerank/fast

#=============================================================================
# Target rules for targets named main-pagerank

# Build rule for target.
main-pagerank: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-pagerank
.PHONY : main-pagerank

# fast build rule for target.
main-pagerank/fast:
	$(MAKE) $(MAKESILENT) -f pagerank/CMakeFiles/main-pagerank.dir/build.make pagerank/CMakeFiles/main-pagerank.dir/build
.PHONY : main-pagerank/fast

#=============================================================================
# Target rules for targets named PageRankLib

# Build rule for target.
PageRankLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PageRankLib
.PHONY : PageRankLib

# fast build rule for target.
PageRankLib/fast:
	$(MAKE) $(MAKESILENT) -f pagerank/CMakeFiles/PageRankLib.dir/build.make pagerank/CMakeFiles/PageRankLib.dir/build
.PHONY : PageRankLib/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BFSLib"
	@echo "... DataLib"
	@echo "... DijkstraLib"
	@echo "... GraphLib"
	@echo "... NodeLib"
	@echo "... PageRankLib"
	@echo "... main-bfs"
	@echo "... main-data"
	@echo "... main-dijkstra"
	@echo "... main-graph"
	@echo "... main-node"
	@echo "... main-pagerank"
	@echo "... test-bfs"
	@echo "... test-data"
	@echo "... test-dijkstra"
	@echo "... test-graph"
	@echo "... test-node"
	@echo "... test-pagerank"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

